version: '3'

services:
  backend:
    build: ./backend
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - DB_HOST=database
    depends_on:
      - redis
      - database

  frontend:
    build: ./frontend

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
        - ./redis_data:/data

  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./sql_data:/var/lib/postgresql/data

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

