version: '3'

services:
  backend:
    image: backend-example-docker
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - DB_HOST=database
    depends_on:
      - redis
      - database

  frontend:
    image: frontend-example-docker

  redis:
    image: redis

  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=secret

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

